{
	"cve": {
		"data_type": "CVE",
		"data_format": "MITRE",
		"data_version": "4.0",
		"CVE_data_meta": {
			"ID": "CVE-2021-4117",
			"ASSIGNER": "security@huntr.dev"
		},
		"problemtype": {
			"problemtype_data": [
				{
					"description": [
						{
							"lang": "en",
							"value": "CWE-840"
						}
					]
				}
			]
		},
		"references": {
			"reference_data": [
				{
					"url": "https://huntr.dev/bounties/0b81e572-bdc9-4caf-aa02-81f3c7ad7c0a",
					"name": "https://huntr.dev/bounties/0b81e572-bdc9-4caf-aa02-81f3c7ad7c0a",
					"refsource": "CONFIRM",
					"tags": []
				},
				{
					"url": "https://github.com/yetiforcecompany/yetiforcecrm/commit/8dccd93442725f245b4b71986bbe6f4f48639239",
					"name": "https://github.com/yetiforcecompany/yetiforcecrm/commit/8dccd93442725f245b4b71986bbe6f4f48639239",
					"refsource": "MISC",
					"tags": []
				}
			]
		},
		"description": {
			"description_data": [
				{
					"lang": "en",
					"value": "yetiforcecrm is vulnerable to Business Logic Errors"
				}
			]
		}
	},
	"configurations": {
		"CVE_data_version": "4.0",
		"nodes": []
	},
	"impact": {},
	"publishedDate": "2021-12-15T15:15Z",
	"lastModifiedDate": "2021-12-15T15:15Z"
}