{
	"cve": {
		"data_type": "CVE",
		"data_format": "MITRE",
		"data_version": "4.0",
		"CVE_data_meta": {
			"ID": "CVE-2022-3598",
			"ASSIGNER": "cve@gitlab.com"
		},
		"problemtype": {
			"problemtype_data": [
				{
					"description": []
				}
			]
		},
		"references": {
			"reference_data": [
				{
					"url": "https://gitlab.com/gitlab-org/cves/-/blob/master/2022/CVE-2022-3598.json",
					"name": "https://gitlab.com/gitlab-org/cves/-/blob/master/2022/CVE-2022-3598.json",
					"refsource": "CONFIRM",
					"tags": []
				},
				{
					"url": "https://gitlab.com/libtiff/libtiff/-/issues/435",
					"name": "https://gitlab.com/libtiff/libtiff/-/issues/435",
					"refsource": "MISC",
					"tags": []
				},
				{
					"url": "https://gitlab.com/libtiff/libtiff/-/commit/cfbb883bf6ea7bedcb04177cc4e52d304522fdff",
					"name": "https://gitlab.com/libtiff/libtiff/-/commit/cfbb883bf6ea7bedcb04177cc4e52d304522fdff",
					"refsource": "MISC",
					"tags": []
				}
			]
		},
		"description": {
			"description_data": [
				{
					"lang": "en",
					"value": "LibTIFF 4.4.0 has an out-of-bounds write in extractContigSamplesShifted24bits in tools/tiffcrop.c:3604, allowing attackers to cause a denial-of-service via a crafted tiff file. For users that compile libtiff from sources, the fix is available with commit cfbb883b."
				}
			]
		}
	},
	"configurations": {
		"CVE_data_version": "4.0",
		"nodes": []
	},
	"impact": {},
	"publishedDate": "2022-10-21T16:15Z",
	"lastModifiedDate": "2022-10-21T16:42Z"
}