{
	"cve": {
		"data_type": "CVE",
		"data_format": "MITRE",
		"data_version": "4.0",
		"CVE_data_meta": {
			"ID": "CVE-2013-2191",
			"ASSIGNER": "cve@mitre.org"
		},
		"problemtype": {
			"problemtype_data": [
				{
					"description": [
						{
							"lang": "en",
							"value": "CWE-20"
						}
					]
				}
			]
		},
		"references": {
			"reference_data": [
				{
					"url": "http://lists.opensuse.org/opensuse-updates/2013-07/msg00025.html",
					"name": "openSUSE-SU-2013:1154",
					"refsource": "SUSE",
					"tags": []
				},
				{
					"url": "http://lists.opensuse.org/opensuse-updates/2013-07/msg00026.html",
					"name": "openSUSE-SU-2013:1155",
					"refsource": "SUSE",
					"tags": []
				},
				{
					"url": "http://www.openwall.com/lists/oss-security/2013/06/19/6",
					"name": "[oss-security] 20130619 [CVE identifier assignment notification] CVE-2013-2191  python-bugzilla: Does not verify Bugzilla server certificate",
					"refsource": "MLIST",
					"tags": []
				},
				{
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=951594",
					"name": "https://bugzilla.redhat.com/show_bug.cgi?id=951594",
					"refsource": "CONFIRM",
					"tags": []
				},
				{
					"url": "https://git.fedorahosted.org/cgit/python-bugzilla.git/commit/?id=a782282ee479ba4cc1b8b1d89700ac630ba83eef",
					"name": "https://git.fedorahosted.org/cgit/python-bugzilla.git/commit/?id=a782282ee479ba4cc1b8b1d89700ac630ba83eef",
					"refsource": "CONFIRM",
					"tags": [
						"Patch"
					]
				},
				{
					"url": "https://lists.fedorahosted.org/pipermail/python-bugzilla/2013-June/000104.html",
					"name": "[python-bugzilla] 20130619 ANNOUNCE: python-bugzilla 0.9.0 released",
					"refsource": "MLIST",
					"tags": []
				}
			]
		},
		"description": {
			"description_data": [
				{
					"lang": "en",
					"value": "python-bugzilla before 0.9.0 does not validate X.509 certificates, which allows man-in-the-middle attackers to spoof Bugzilla servers via a crafted certificate."
				}
			]
		}
	},
	"configurations": {
		"CVE_data_version": "4.0",
		"nodes": [
			{
				"operator": "OR",
				"cpe_match": [
					{
						"vulnerable": true,
						"cpe23Uri": "cpe:2.3:a:python_bugzilla_project:python-bugzilla:0.6.0:*:*:*:*:*:*:*"
					},
					{
						"vulnerable": true,
						"cpe23Uri": "cpe:2.3:a:python_bugzilla_project:python-bugzilla:0.6.1:*:*:*:*:*:*:*"
					},
					{
						"vulnerable": true,
						"cpe23Uri": "cpe:2.3:a:python_bugzilla_project:python-bugzilla:0.6.2:*:*:*:*:*:*:*"
					},
					{
						"vulnerable": true,
						"cpe23Uri": "cpe:2.3:a:python_bugzilla_project:python-bugzilla:0.7.0:*:*:*:*:*:*:*"
					},
					{
						"vulnerable": true,
						"cpe23Uri": "cpe:2.3:a:python_bugzilla_project:python-bugzilla:*:*:*:*:*:*:*:*",
						"versionEndIncluding": "0.8.0"
					}
				]
			},
			{
				"operator": "OR",
				"cpe_match": [
					{
						"vulnerable": true,
						"cpe23Uri": "cpe:2.3:o:fedoraproject:fedora:17:*:*:*:*:*:*:*"
					},
					{
						"vulnerable": true,
						"cpe23Uri": "cpe:2.3:o:fedoraproject:fedora:18:*:*:*:*:*:*:*"
					},
					{
						"vulnerable": true,
						"cpe23Uri": "cpe:2.3:o:opensuse:opensuse:11.4:*:*:*:*:*:*:*"
					},
					{
						"vulnerable": true,
						"cpe23Uri": "cpe:2.3:o:opensuse:opensuse:12.2:*:*:*:*:*:*:*"
					},
					{
						"vulnerable": true,
						"cpe23Uri": "cpe:2.3:o:opensuse:opensuse:12.3:*:*:*:*:*:*:*"
					}
				]
			}
		]
	},
	"impact": {
		"baseMetricV2": {
			"cvssV2": {
				"version": "2.0",
				"vectorString": "AV:N/AC:M/Au:N/C:N/I:P/A:N",
				"accessVector": "NETWORK",
				"accessComplexity": "MEDIUM",
				"authentication": "NONE",
				"confidentialityImpact": "NONE",
				"integrityImpact": "PARTIAL",
				"availabilityImpact": "NONE",
				"baseScore": 4.3
			},
			"severity": "MEDIUM",
			"exploitabilityScore": 8.6,
			"impactScore": 2.9,
			"obtainAllPrivilege": false,
			"obtainUserPrivilege": false,
			"obtainOtherPrivilege": false,
			"userInteractionRequired": false
		}
	},
	"publishedDate": "2014-02-08T00:55Z",
	"lastModifiedDate": "2018-10-30T16:27Z"
}