{
	"cve": {
		"data_type": "CVE",
		"data_format": "MITRE",
		"data_version": "4.0",
		"CVE_data_meta": {
			"ID": "CVE-2021-32560",
			"ASSIGNER": "cve@mitre.org"
		},
		"problemtype": {
			"problemtype_data": [
				{
					"description": []
				}
			]
		},
		"references": {
			"reference_data": [
				{
					"url": "https://github.com/OctoPrint/OctoPrint/releases/tag/1.6.0",
					"name": "https://github.com/OctoPrint/OctoPrint/releases/tag/1.6.0",
					"refsource": "MISC",
					"tags": []
				},
				{
					"url": "https://www.brzozowski.io",
					"name": "https://www.brzozowski.io",
					"refsource": "MISC",
					"tags": []
				},
				{
					"url": "https://octoprint.org/blog/2021/04/27/new-release-1.6.0/",
					"name": "https://octoprint.org/blog/2021/04/27/new-release-1.6.0/",
					"refsource": "MISC",
					"tags": []
				}
			]
		},
		"description": {
			"description_data": [
				{
					"lang": "en",
					"value": "The Logging subsystem in OctoPrint before 1.6.0 has incorrect access control because it attempts to manage files that are not *.log files."
				}
			]
		}
	},
	"configurations": {
		"CVE_data_version": "4.0",
		"nodes": []
	},
	"impact": {},
	"publishedDate": "2021-05-11T14:15Z",
	"lastModifiedDate": "2021-05-11T14:15Z"
}